version: 2.1

commands:
  install-validate:
    steps:
      - checkout
      - run: yarn
      - run: yarn validate
  create-artifact:
    parameters:
      path: 
        type: string
      archive-name:
        type: string
    steps:
      - run: mkdir ~/artifact
      - run: tar -cvf ~/artifact/<< parameters.archive-name >>.tar << parameters.path >>
      - store_artifacts:
          path: ~/artifact/<< parameters.archive-name >>.tar

jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine

    working_directory: ~/windows

    steps:
      - install-validate
      - run: yarn build:win
      - create-artifact:
          path: ~/windows/build/
          archive-name: build

  build_linux:
    docker:
      - image: electronuserland/builder

    working_directory: ~/linux

    steps:
      - install-validate
      - run: yarn build:linux
      - create-artifact:
          path: ~/linux/build/
          archive-name: build

workflows:
  build:
    jobs:
      - build_windows
      - build_linux