import { Theme } from '@fm/common';

const DEFAULT_THEME: Theme = {
  'primary.textColor': '#CDD1C4',
  'primary.backgroundColor': '#30323D',
  'primary.fontFamily': 'Maven Pro',
  'primary.fontSize': 15,
  'primary.hoverColor': '#4a4c56',
  'primary.selectedColor': '#70727e',
  'primary.additionalColor': '#70727e',

  'explorer.backgroundColor': '#30323D',
  'explorer.textColor': '#CDD1C4',
  'explorer.hoverColor': '#4a4c56',
  'explorer.selectedColor': '#70727e',
  'explorer.fontFamily': 'Maven Pro',
  'explorer.fontSize': 15,

  'preview.backgroundColor': '#30323D',
  'preview.textColor': '#CDD1C4',
  'preview.fontFamily': 'Consolas',

  'terminal.backgroundColor': '#30323D',
  'terminal.blackColor': '#2e3436',
  'terminal.blueColor': '#3465a4',
  'terminal.brightBlackColor': '#555753',
  'terminal.brightBlueColor': '#729fcf',
  'terminal.brightCyanColor': '#34e2e2',
  'terminal.brightGreenColor': '#8ae234',
  'terminal.brightMagentaColor': '#ad7fa8',
  'terminal.brightRedColor': '#ef2929',
  'terminal.brightWhiteColor': '#eeeeec',
  'terminal.brightYellowColor': '#fce94f',
  'terminal.cursorColor': '#ffffff',
  'terminal.cursorAccentColor': '#000000',
  'terminal.cyanColor': '#06989a',
  'terminal.foregroundColor': '#ffffff',
  'terminal.greenColor': '#4e9a06',
  'terminal.magentaColor': '#75507b',
  'terminal.redColor': '#cc0000',
  'terminal.selectionColor': 'rgba(255, 255, 255, 0.3)',
  'terminal.whiteColor': '#d3d7cf',
  'terminal.yellowColor': '#c4a000',
  'terminal.fontFamily': 'Consolas',
  'terminal.fontSize': 15,

  'palette.backgroundColor': '#30323D',
  'palette.textColor': '#CDD1C4',
  'palette.fontFamily': 'Maven Pro',
  'palette.fontSize': 15,
  'palette.hoverColor': '#4a4c56',
  'palette.selectedColor': '#70727e',
  'palette.additionalColor': '#70727e',
};

export { DEFAULT_THEME };
