const Channels = {
  GET_SETTINGS: 'get-settings',
  SET_SETTINGS: 'set-settings-value',
  RESET_SETTINGS: 'reset-settings',
  SETTINGS: 'settings',
  OPEN_SETTINGS: 'open-settings',
  SAVE_SETTINGS: 'save-settings',
  THEME: 'theme',
  SET_THEME: 'set-theme',
  RESET_THEME: 'reset-theme',
  GET_THEME: 'get-theme',
  OPEN_THEME: 'open-theme',
  ADD_PATH: 'add-path',
  GET_PATH: 'get-path',
  PATH: 'path',
  GET_KEYMAP: 'get-keymap',
  RESET_KEYMAP: 'reset-keymap',
  KEYMAP: 'keymap',
  BEFORE_QUIT: 'before-quit',
  GET_LAYOUT: 'get-layout',
  SAVE_LAYOUT: 'save-layout',
  LAYOUT: 'layout',
  QUITTER: 'quitter',
  KEYPRESS: 'keypress',
};

export { Channels };
